server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/ValBernaola/Microservicios-sd
          search-paths: config-data
  application:
    name: config-service
